language: node_js
node_js:
- '10'
- '12'
- '14'
dist: trusty
sudo: required
env:
  global:
  - NODE_ENV=test
  - PINO_EVENT_HUB_NAMESPACE=pinoeventhubns
  - PINO_EVENT_HUB=pinoeventhub
  - PINO_SHARED_ACCESS_POLICY_NAME=sendPinoEvent
script:
  - npm run lint
  - npm run test

after_script:
  - npm run coveralls